import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
FButtonStyles buttonStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required bool touch,
}) {
  final primary = _buttonSizeStyles(
    typography: typography,
    style: style,
    touch: touch,
    decoration: (radius) => .from(
      ShapeDecoration(
        shape: RoundedSuperellipseBorder(borderRadius: radius),
        color: colors.primary,
      ),
      variants: {
        [.hovered, .pressed]: .shapeDelta(color: colors.hover(colors.primary)),
        [.disabled]: .shapeDelta(color: colors.disable(colors.primary)),
        [.selected]: .shapeDelta(color: colors.hover(colors.primary)),
        [.selected.and(.disabled)]: .shapeDelta(
          color: colors.disable(colors.hover(colors.primary)),
        ),
      },
    ),
    foregroundColor: colors.primaryForeground,
    disabledForegroundColor: colors.disable(colors.primaryForeground),
  );

  return FButtonStyles(
    FVariants(
      primary,
      variants: {
        [.primary]: primary,
        [.secondary]: _buttonSizeStyles(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(borderRadius: radius),
              color: colors.secondary,
            ),
            variants: {
              [.hovered, .pressed]: .shapeDelta(
                color: colors.hover(colors.secondary),
              ),
              [.disabled]: .shapeDelta(color: colors.disable(colors.secondary)),
              [.selected]: .shapeDelta(color: colors.hover(colors.secondary)),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(colors.hover(colors.secondary)),
              ),
            },
          ),
          foregroundColor: colors.secondaryForeground,
          disabledForegroundColor: colors.disable(colors.secondaryForeground),
        ),
        [.destructive]: _buttonSizeStyles(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(borderRadius: radius),
              color: colors.destructive.withValues(
                alpha: colors.brightness == .light ? 0.1 : 0.2,
              ),
            ),
            variants: {
              [.hovered, .pressed]: .shapeDelta(
                color: colors.destructive.withValues(
                  alpha: colors.brightness == .light ? 0.2 : 0.3,
                ),
              ),
              [.disabled]: .shapeDelta(
                color: colors.destructive.withValues(
                  alpha: colors.brightness == .light ? 0.05 : 0.1,
                ),
              ),
              [.selected]: .shapeDelta(
                color: colors.destructive.withValues(
                  alpha: colors.brightness == .light ? 0.2 : 0.3,
                ),
              ),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(
                  colors.destructive.withValues(
                    alpha: colors.brightness == .light ? 0.2 : 0.3,
                  ),
                ),
              ),
            },
          ),
          foregroundColor: colors.destructive,
          disabledForegroundColor: colors.destructive.withValues(alpha: 0.5),
        ),
        [.outline]: _buttonSizeStyles(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(
                side: BorderSide(
                  color: colors.border,
                  width: style.borderWidth,
                ),
                borderRadius: radius,
              ),
              color: colors.card,
            ),
            variants: {
              [.hovered, .pressed]: .shapeDelta(color: colors.secondary),
              [.disabled]: .shapeDelta(color: colors.disable(colors.card)),
              [.selected]: .shapeDelta(color: colors.secondary),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(colors.secondary),
              ),
            },
          ),
          foregroundColor: colors.secondaryForeground,
          disabledForegroundColor: colors.disable(colors.secondaryForeground),
        ),
        [.ghost]: _buttonSizeStyles(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(borderRadius: radius),
            ),
            variants: {
              [.hovered, .pressed]: .shapeDelta(color: colors.secondary),
              [.disabled]: const .shapeDelta(),
              [.selected]: .shapeDelta(color: colors.secondary),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(colors.secondary),
              ),
            },
          ),
          foregroundColor: colors.secondaryForeground,
          disabledForegroundColor: colors.disable(colors.secondaryForeground),
        ),
      },
    ),
  );
}

FButtonSizeStyles _buttonSizeStyles({
  required FTypography typography,
  required FStyle style,
  required bool touch,
  required FVariants<
    FTappableVariantConstraint,
    FTappableVariant,
    Decoration,
    DecorationDelta
  >
  Function(BorderRadiusGeometry radius)
  decoration,
  required Color foregroundColor,
  required Color disabledForegroundColor,
}) {
  if (touch) {
    final md = _buttonStyle(
      style: style,
      decoration: decoration(style.borderRadius.md),
      foregroundColor: foregroundColor,
      disabledForegroundColor: disabledForegroundColor,
      textStyle: typography.body.sm,
      contentConstraints: const BoxConstraints(minWidth: 44, minHeight: 44),
      contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
      contentSpacing: 6,
      iconConstraints: const BoxConstraints(minWidth: 44, minHeight: 44),
      iconSize: typography.body.md.fontSize ?? 18,
      iconPadding: const EdgeInsets.all(13),
    );

    return FButtonSizeStyles(
      FVariants(
        md,
        variants: {
          [.xs]: _buttonStyle(
            style: style,
            decoration: decoration(style.borderRadius.sm),
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            textStyle: typography.body.xs,
            contentConstraints: const BoxConstraints(
              minWidth: 32,
              minHeight: 32,
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 10,
              vertical: 9,
            ),
            contentSpacing: 4,
            iconConstraints: const BoxConstraints(minWidth: 32, minHeight: 32),
            iconSize: typography.body.sm.fontSize ?? 16,
            iconPadding: const EdgeInsets.all(8),
          ),
          [.sm]: _buttonStyle(
            style: style,
            decoration: decoration(style.borderRadius.md),
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            textStyle: typography.body.sm,
            contentConstraints: const BoxConstraints(
              minWidth: 40,
              minHeight: 40,
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 12,
              vertical: 12,
            ),
            contentSpacing: 4,
            iconConstraints: const BoxConstraints(minWidth: 40, minHeight: 40),
            iconSize: typography.body.md.fontSize ?? 18,
            iconPadding: const EdgeInsets.all(11),
          ),
          [.md]: md,
          [.lg]: _buttonStyle(
            style: style,
            decoration: decoration(style.borderRadius.md),
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            textStyle: typography.body.sm,
            contentConstraints: const BoxConstraints(
              minWidth: 48,
              minHeight: 48,
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 12,
              vertical: 16,
            ),
            contentSpacing: 6,
            iconConstraints: const BoxConstraints(minWidth: 48, minHeight: 48),
            iconSize: typography.body.lg.fontSize ?? 20,
            iconPadding: const EdgeInsets.all(14),
          ),
        },
      ),
    );
  }

  final md = _buttonStyle(
    style: style,
    decoration: decoration(style.borderRadius.md),
    foregroundColor: foregroundColor,
    disabledForegroundColor: disabledForegroundColor,
    textStyle: typography.body.sm,
    contentConstraints: const BoxConstraints(minWidth: 36, minHeight: 36),
    contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 11),
    contentSpacing: 6,
    iconConstraints: const BoxConstraints(minWidth: 36, minHeight: 36),
    iconSize: typography.body.md.fontSize ?? 16,
    iconPadding: const EdgeInsets.all(10),
  );

  return FButtonSizeStyles(
    FVariants(
      md,
      variants: {
        [.xs]: _buttonStyle(
          style: style,
          decoration: decoration(style.borderRadius.sm),
          foregroundColor: foregroundColor,
          disabledForegroundColor: disabledForegroundColor,
          textStyle: typography.body.xs,
          contentConstraints: const BoxConstraints(minWidth: 24, minHeight: 24),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 8,
            vertical: 6,
          ),
          contentSpacing: 4,
          iconConstraints: const BoxConstraints(minWidth: 24, minHeight: 24),
          iconSize: typography.body.sm.fontSize ?? 14,
          iconPadding: const EdgeInsets.all(5),
        ),
        [.sm]: _buttonStyle(
          style: style,
          decoration: decoration(style.borderRadius.md),
          foregroundColor: foregroundColor,
          disabledForegroundColor: disabledForegroundColor,
          textStyle: typography.body.sm,
          contentConstraints: const BoxConstraints(minWidth: 32, minHeight: 32),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 10,
            vertical: 9,
          ),
          contentSpacing: 4,
          iconConstraints: const BoxConstraints(minWidth: 32, minHeight: 32),
          iconSize: typography.body.md.fontSize ?? 16,
          iconPadding: const EdgeInsets.all(8),
        ),
        [.md]: md,
        [.lg]: _buttonStyle(
          style: style,
          decoration: decoration(style.borderRadius.md),
          foregroundColor: foregroundColor,
          disabledForegroundColor: disabledForegroundColor,
          textStyle: typography.body.sm,
          contentConstraints: const BoxConstraints(minWidth: 40, minHeight: 40),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 10,
            vertical: 13,
          ),
          contentSpacing: 6,
          iconConstraints: const BoxConstraints(minWidth: 40, minHeight: 40),
          iconSize: typography.body.lg.fontSize ?? 18,
          iconPadding: const EdgeInsets.all(11),
        ),
      },
    ),
  );
}

FButtonStyle _buttonStyle({
  required FStyle style,
  required FVariants<
    FTappableVariantConstraint,
    FTappableVariant,
    Decoration,
    DecorationDelta
  >
  decoration,
  required Color foregroundColor,
  required Color disabledForegroundColor,
  required TextStyle textStyle,
  required BoxConstraints contentConstraints,
  required EdgeInsetsGeometry contentPadding,
  required double contentSpacing,
  required BoxConstraints iconConstraints,
  required double iconSize,
  required EdgeInsetsGeometry iconPadding,
}) => FButtonStyle(
  decoration: decoration,
  focusedOutlineStyle: style.focusedOutlineStyle,
  contentStyle: FButtonContentStyle(
    textStyle: FVariants.from(
      textStyle.copyWith(color: foregroundColor, fontWeight: .w500, height: 1),
      variants: {
        [.disabled]: .delta(color: disabledForegroundColor),
      },
    ),
    iconStyle: FVariants.from(
      IconThemeData(color: foregroundColor, size: iconSize),
      variants: {
        [.disabled]: .delta(color: disabledForegroundColor),
      },
    ),
    circularProgressStyle: FVariants.from(
      FCircularProgressStyle(
        iconStyle: IconThemeData(color: foregroundColor, size: iconSize),
      ),
      variants: {
        [.disabled]: .delta(iconStyle: .delta(color: disabledForegroundColor)),
      },
    ),
    padding: contentPadding,
    spacing: contentSpacing,
    constraints: contentConstraints,
  ),
  iconContentStyle: FButtonIconContentStyle(
    iconStyle: FVariants.from(
      IconThemeData(color: foregroundColor, size: iconSize),
      variants: {
        [.disabled]: .delta(color: disabledForegroundColor),
      },
    ),
    padding: iconPadding,
    constraints: iconConstraints,
  ),
  tappableStyle: style.tappableStyle,
);

/// Creates a custom [FButtonStyle] with explicit decoration and foreground.
FButtonStyle buttonStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required Color color,
  required Color foregroundColor,
}) {
  final disabledForeground = colors.disable(foregroundColor);
  return _buttonStyle(
    style: style,
    decoration: FVariants.from(
      ShapeDecoration(
        shape: RoundedSuperellipseBorder(
          borderRadius: style.borderRadius.md,
          side: BorderSide(
            color: foregroundColor.withValues(alpha: .5),
            width: style.borderWidth,
          ),
        ),
        color: color,
      ),
      variants: {
        [.disabled]: .shapeDelta(color: colors.disable(color)),
        [.hovered, .pressed]: .shapeDelta(color: colors.hover(color)),
      },
    ),
    foregroundColor: foregroundColor,
    disabledForegroundColor: disabledForeground,
    textStyle: typography.body.md,
    contentConstraints: const BoxConstraints(minWidth: 36, minHeight: 36),
    contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 11),
    contentSpacing: 6,
    iconConstraints: const BoxConstraints(minWidth: 36, minHeight: 36),
    iconSize: typography.body.md.fontSize ?? 16,
    iconPadding: const EdgeInsets.all(10),
  );
}

/// Creates a [FButtonStyle] for a close button.
FButtonStyle closeButtonStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) {
  final isLight = colors.background.computeLuminance() > 0.5;
  final hoverColor = isLight
      ? const Color(0xFFb91c1c)
      : const Color(0xFFef4444);

  return _windowButton(
    colors: colors,
    typography: typography,
    style: style,
    hoverBg: Colors.red.withValues(alpha: isLight ? 0.1 : 0.2),
    hoverColor: hoverColor,
    normalColor: colors.mutedForeground,
    normalBorder: colors.border,
  );
}

/// Creates a [FButtonStyle] for window control buttons (minimize, maximize).
FButtonStyle windowControlButtonStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) {
  return _windowButton(
    colors: colors,
    typography: typography,
    style: style,
    hoverBg: colors.muted.withValues(alpha: 0.7),
    hoverColor: colors.foreground,
    normalColor: colors.mutedForeground,
    normalBorder: colors.border,
    borderRadius: BorderRadius.circular(6),
  );
}

FButtonStyle _windowButton({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required Color hoverBg,
  required Color hoverColor,
  required Color normalColor,
  required Color normalBorder,
  BorderRadiusGeometry? borderRadius,
}) {
  final radius = borderRadius ?? style.borderRadius.md;
  final disabledColor = colors.disable(normalColor);

  return FButtonStyle(
    decoration: FVariants.from(
      ShapeDecoration(
        shape: RoundedSuperellipseBorder(
          borderRadius: radius,
          side: BorderSide(color: normalBorder, width: style.borderWidth),
        ),
        color: Colors.transparent,
      ),
      variants: {
        [.hovered]: .shapeDelta(color: hoverBg),
      },
    ),
    focusedOutlineStyle: style.focusedOutlineStyle,
    contentStyle: FButtonContentStyle(
      circularProgressStyle: FVariants.from(
        FCircularProgressStyle(
          iconStyle: IconThemeData(color: normalColor, size: 14),
        ),
        variants: {
          [.hovered]: .delta(iconStyle: .delta(color: hoverColor)),
          [.disabled]: .delta(iconStyle: .delta(color: disabledColor)),
        },
      ),
      textStyle: FVariants.from(
        typography.body.sm.copyWith(
          color: normalColor,
          fontWeight: .w500,
          height: 1,
        ),
        variants: {
          [.hovered]: .delta(color: hoverColor),
          [.disabled]: .delta(color: disabledColor),
        },
      ),
      iconStyle: FVariants.from(
        IconThemeData(color: normalColor, size: 14),
        variants: {
          [.hovered]: .delta(color: hoverColor),
          [.disabled]: .delta(color: disabledColor),
        },
      ),
      padding: const EdgeInsets.all(7),
      spacing: 0,
      constraints: const BoxConstraints(minWidth: 32, minHeight: 32),
    ),
    iconContentStyle: FButtonIconContentStyle(
      iconStyle: FVariants.from(
        IconThemeData(color: normalColor, size: 14),
        variants: {
          [.hovered]: .delta(color: hoverColor),
          [.disabled]: .delta(color: disabledColor),
        },
      ),
      padding: const EdgeInsets.all(7),
      constraints: const BoxConstraints(minWidth: 32, minHeight: 32),
    ),
    tappableStyle: style.tappableStyle,
  );
}

/// Segmented layout toggle chip used in the Quran header.
FButtonStyle layoutSegmentButtonStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required BorderRadiusGeometry borderRadius,
  bool compact = false,
}) {
  final selectedBorder = RoundedSuperellipseBorder(
    side: BorderSide(color: colors.primary.withValues(alpha: 0.35)),
    borderRadius: borderRadius,
  );
  final baseShape = RoundedSuperellipseBorder(borderRadius: borderRadius);
  final selectedShadow = [
    BoxShadow(
      color: colors.barrier.withValues(alpha: 0.05),
      blurRadius: 6,
      offset: const Offset(0, 1),
    ),
  ];

  final decoration =
      FVariants<
        FTappableVariantConstraint,
        FTappableVariant,
        Decoration,
        DecorationDelta
      >.from(
        ShapeDecoration(shape: baseShape, color: Colors.transparent),
        variants: {
          [FTappableVariant.hovered, FTappableVariant.pressed]:
              DecorationDelta.shapeDelta(color: colors.card),
          [FTappableVariant.selected]: DecorationDelta.shapeDelta(
            color: colors.card,
            shape: selectedBorder,
            shadows: selectedShadow,
          ),
        },
      );

  final textStyle = typography.body.xs.copyWith(
    color: colors.mutedForeground,
    fontWeight: FontWeight.w500,
    height: 1,
  );

  return FButtonStyle(
    decoration: decoration,
    focusedOutlineStyle: style.focusedOutlineStyle,
    contentStyle: FButtonContentStyle(
      textStyle: FVariants.from(
        textStyle,
        variants: {
          [.selected]: TextStyleDelta.delta(
            color: colors.foreground,
            fontWeight: FontWeight.w600,
          ),
        },
      ),
      iconStyle: FVariants.from(
        IconThemeData(color: colors.mutedForeground, size: 16),
        variants: {
          [.selected]: IconThemeDataDelta.delta(color: colors.primary),
        },
      ),
      circularProgressStyle: FVariants.from(
        FCircularProgressStyle(
          iconStyle: IconThemeData(color: colors.mutedForeground, size: 16),
        ),
        variants: {
          [.selected]: FCircularProgressStyleDelta.delta(
            iconStyle: IconThemeDataDelta.delta(color: colors.primary),
          ),
        },
      ),
      padding: EdgeInsets.symmetric(
        horizontal: compact ? 8 : 12,
        vertical: 8,
      ),
      spacing: 4,
    ),
    iconContentStyle: FButtonIconContentStyle(
      iconStyle: FVariants.from(
        IconThemeData(color: colors.mutedForeground, size: 16),
        variants: {
          [.selected]: IconThemeDataDelta.delta(color: colors.primary),
        },
      ),
      padding: const EdgeInsets.all(8),
    ),
    tappableStyle: style.tappableStyle,
  );
}

