import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

/// Generates [lib/src/data/mushaf_page_index.dart] from mushaf_reader Hafs JSON.
///
/// Run from `packages/hisn_elmoslem`:
/// ```bash
/// dart run tool/generate_mushaf_page_index.dart
/// ```
Future<void> main() async {
  final packageRoot = Directory.current.path;
  final jsonPath = p.normalize(
    p.join(
      packageRoot,
      '..',
      'mushaf_reader',
      'assets',
      'jsons',
      'quran_hafs.json',
    ),
  );

  final jsonFile = File(jsonPath);
  if (!jsonFile.existsSync()) {
    stderr.writeln('Missing $jsonPath');
    exitCode = 1;
    return;
  }

  final rows = json.decode(jsonFile.readAsStringSync()) as List<dynamic>;
  final pages = List<int>.filled(6237, 0);

  for (final row in rows) {
    final map = row as Map<String, dynamic>;
    final id = map['id'] as int;
    final page = map['page'] as int;
    if (id >= 1 && id <= 6236) {
      pages[id] = page;
    }
  }

  for (var id = 1; id <= 6236; id++) {
    if (pages[id] == 0) {
      stderr.writeln('Missing page for ayah id $id');
      exitCode = 1;
      return;
    }
  }

  final buffer = StringBuffer('''
// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by: dart run tool/generate_mushaf_page_index.dart
// Source: packages/mushaf_reader/assets/jsons/quran_hafs.json
//
// ignore_for_file: lines_longer_than_80_chars

/// Madinah Mushaf page lookup (Hafs, 604 pages).
abstract final class MushafPageIndex {
  /// Total ayahs in the Mushaf.
  static const int totalAyahs = 6236;

  /// Ayah count per surah (1–114).
  static const List<int> ayahsPerSurah = <int>[
    7, 286, 200, 176, 120, 165, 206, 75, 129, 109, 123, 111, 43, 52, 99,
    128, 111, 110, 98, 135, 112, 78, 118, 64, 77, 227, 93, 88, 69, 60, 34,
    30, 73, 54, 45, 83, 182, 88, 75, 85, 54, 53, 89, 59, 37, 35, 38, 29, 18,
    45, 60, 49, 62, 55, 78, 96, 29, 22, 24, 13, 14, 11, 11, 18, 12, 12, 30,
    52, 52, 44, 28, 28, 20, 56, 40, 31, 50, 40, 46, 42, 29, 19, 36, 25, 22,
    17, 19, 26, 30, 20, 15, 21, 11, 8, 8, 19, 5, 8, 8, 11, 11, 8, 3, 9, 5,
    4, 7, 3, 6, 3, 5, 4, 5, 6,
  ];

  /// Mushaf page (1–604) for each global ayah id (index 1–6236).
  static const List<int> pageByGlobalId = <int>[
    0,
''');

  for (var id = 1; id <= 6236; id++) {
    buffer.writeln('    ${pages[id]},');
  }

  buffer.writeln('  ];');
  buffer.writeln('}');

  final outPath = p.join(
    packageRoot,
    'lib',
    'src',
    'data',
    'mushaf_page_index.dart',
  );
  await Directory(p.dirname(outPath)).create(recursive: true);
  await File(outPath).writeAsString(buffer.toString());
  stdout.writeln('Wrote ${p.basename(outPath)}');
}
